import "bootstrap/dist/css/bootstrap.min.css"
import "@fortawesome/fontawesome-free/css/all.min.css"
import "../globals.css";
import "../responsive.css";
import ClientLayout from "@/components/ClientLayout";
import Footer from "@/components/Footer";
import AOSInit from "@/components/AOSInit";
import Header from "@/components/Header";
import { SideBarProvider } from "../context";
import SideBar from "@/components/side-bar";
import MagicCursor from "@/components/MagicCursor";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AOSInit />
      <MagicCursor />
        <SideBarProvider>
          <SideBar/>
          <ClientLayout>
            <Header />
            <main>{children}</main>
            <Footer />
          </ClientLayout>
        </SideBarProvider>
      </body>
    </html>
  );
}
